# Generated by Django 5.1.6 on 2025-02-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dinedashapp",
            "0002_blogpost_alter_user_options_alter_user_managers_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                ("hours_sunday", models.TimeField(null=True)),
                ("hours_monday", models.TimeField(null=True)),
                ("hours_tuesday", models.TimeField(null=True)),
                ("hours_wednesday", models.TimeField(null=True)),
                ("hours_thursday", models.TimeField(null=True)),
                ("hours_friday", models.TimeField(null=True)),
                ("hours_saturday", models.TimeField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.CharField(max_length=1000)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dinedashapp.restaurant",
                    ),
                ),
            ],
        ),
    ]
