# Generated by Django 5.1.6 on 2025-02-23 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0003_restaurant_alter_blogpost_options_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="dinedashapp.restaurant",
            ),
        ),
    ]
