# Generated by Django 5.1.6 on 2025-02-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dinedashapp",
            "0005_alter_menuitem_options_alter_restaurant_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_friday",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_monday",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_saturday",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_sunday",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_thursday",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_tuesday",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="hours_wednesday",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_friday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_monday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_saturday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_sunday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_thursday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_tuesday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_hour_wednesday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_friday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_monday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_saturday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_sunday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_thursday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_tuesday",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_hour_wednesday",
            field=models.TimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_sunday__isnull", True),
                        ("open_hour_sunday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_sunday__isnull", False),
                        ("open_hour_sunday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sunday_both_null_or_neither_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_monday__isnull", True),
                        ("open_hour_monday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_monday__isnull", False),
                        ("open_hour_monday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="monday_both_null_or_neither_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_tuesday__isnull", True),
                        ("open_hour_tuesday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_tuesday__isnull", False),
                        ("open_hour_tuesday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="tuesday_both_null_or_neither_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_wednesday__isnull", True),
                        ("open_hour_wednesday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_wednesday__isnull", False),
                        ("open_hour_wednesday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="wednesday_both_null_or_neither_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_thursday__isnull", True),
                        ("open_hour_thursday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_thursday__isnull", False),
                        ("open_hour_thursday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="thursday_both_null_or_neither_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_friday__isnull", True),
                        ("open_hour_friday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_friday__isnull", False),
                        ("open_hour_friday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="friday_both_null_or_neither_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("close_hour_saturday__isnull", True),
                        ("open_hour_saturday__isnull", True),
                    ),
                    models.Q(
                        ("close_hour_saturday__isnull", False),
                        ("open_hour_saturday__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="saturday_both_null_or_neither_null",
            ),
        ),
    ]
