# Generated by Django 5.1.6 on 2025-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0010_restaurantreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinfo",
            name="location",
            field=models.CharField(
                max_length=300, null=True, verbose_name="defaultlocation"
            ),
        ),
        migrations.AddField(
            model_name="customerinfo",
            name="location_x_coordinate",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="customerinfo",
            name="location_y_coordinate",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="location",
            field=models.CharField(
                default="0", max_length=300, verbose_name="location"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="location_x_coordinate",
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="location_y_coordinate",
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
