# Generated by Django 5.1.7 on 2025-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0011_customerinfo_location_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_sunday__lt", models.F("close_hour_sunday"))
                ),
                name="sunday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Sunday's opening hour must be earlier than its closing hour.",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_monday__lt", models.F("close_hour_monday"))
                ),
                name="monday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Monday's opening hour must be earlier than its closing hour.",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_tuesday__lt", models.F("close_hour_tuesday"))
                ),
                name="tuesday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Tuesday's opening hour must be earlier than its closing hour.",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_wednesday__lt", models.F("close_hour_wednesday"))
                ),
                name="wednesday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Wednesday's opening hour must be earlier than its closing hour.",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_thursday__lt", models.F("close_hour_thursday"))
                ),
                name="thursday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Thursday's opening hour must be earlier than its closing hour.",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_friday__lt", models.F("close_hour_friday"))
                ),
                name="friday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Friday's opening hour must be earlier than its closing hour.",
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("open_hour_saturday__lt", models.F("close_hour_saturday"))
                ),
                name="saturday_open_hour_must_be_earlier_than_close_hour",
                violation_error_message="Saturday's opening hour must be earlier than its closing hour.",
            ),
        ),
    ]
