# Generated by Django 5.1.7 on 2025-03-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dinedashapp",
            "0012_restaurant_sunday_open_hour_must_be_earlier_than_close_hour_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerinfo",
            name="location",
            field=models.CharField(max_length=300, null=True, verbose_name="location"),
        ),
    ]
