# Generated by Django 5.1.7 on 2025-04-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0013_alter_customerinfo_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="favorited_by",
            field=models.ManyToManyField(
                related_name="favorite_restaurants", to="dinedashapp.customerinfo"
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurantreview",
            constraint=models.UniqueConstraint(
                fields=("user", "restaurant"),
                name="at_most_one_review_per_restaurant_per_user",
            ),
        ),
    ]
