# Generated by Django 5.1.7 on 2025-04-04 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0014_restaurant_favorited_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Np", "Not placed yet"),
                            ("Pl", "Placed"),
                            ("Ip", "In progress"),
                            ("De", "Delivered"),
                        ],
                        default="Np",
                        max_length=2,
                    ),
                ),
                ("date_placed", models.DateTimeField(null=True)),
                ("date_delivered", models.DateTimeField(null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="dinedashapp.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="dinedashapp.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dinedashapp.order",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_item__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("menu_item", "order"),
                        name="menu_item_can_only_appear_once_in_order",
                    )
                ],
            },
        ),
    ]
