# Generated by Django 5.1.7 on 2025-04-04 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0015_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="date_delivered",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="date_placed",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Cr", "Credit card"), ("De", "Debit card")],
                        max_length=2,
                    ),
                ),
                (
                    "cardholder_name",
                    models.CharField(max_length=300, verbose_name="Full name on card"),
                ),
                ("billing_address", models.CharField(max_length=300, null=True)),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        validators=[django.core.validators.MinLengthValidator(16)],
                    ),
                ),
                (
                    "expiration_month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("expiration_year", models.PositiveSmallIntegerField()),
                (
                    "cvv",
                    models.CharField(
                        max_length=4,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="CVV",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="dinedashapp.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
