# Generated by Django 5.1.7 on 2025-04-10 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0016_orderitem_date_delivered_orderitem_date_placed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["date_placed", "id"]},
        ),
        migrations.AddField(
            model_name="deliverycontractorinfo",
            name="location",
            field=models.CharField(
                default="nothing", max_length=300, verbose_name="location"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverycontractorinfo",
            name="location_x_coordinate",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverycontractorinfo",
            name="location_y_coordinate",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="accepted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_orders",
                to="dinedashapp.deliverycontractorinfo",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_by",
            field=models.ManyToManyField(
                related_name="rejected_orders", to="dinedashapp.deliverycontractorinfo"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Np", "Not placed yet"),
                    ("Pl", "Placed"),
                    ("Rp", "Ready to be picked up for delivery"),
                    ("It", "In transit"),
                    ("De", "Delivered"),
                ],
                default="Np",
                max_length=2,
            ),
        ),
    ]
