# Generated by Django 5.1.8 on 2025-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dinedashapp",
            "0017_alter_order_options_deliverycontractorinfo_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="minutes_away",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
