# Generated by Django 5.2 on 2025-04-24 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dinedashapp", "0018_order_minutes_away"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_id",
                    models.PositiveSmallIntegerField(verbose_name="table number"),
                ),
                ("capacity", models.PositiveSmallIntegerField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="dinedashapp.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["local_id"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("number_of_guests", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pe", "Pending"),
                            ("Co", "Confirmed"),
                            ("Ca", "Canceled"),
                        ],
                        default="Pe",
                        max_length=2,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="dinedashapp.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="dinedashapp.table",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="capacity_must_be_greater_than_zero",
                violation_error_message="Capacity must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("restaurant_id", "local_id"),
                name="local_id_must_be_unique_for_restaurant",
                violation_error_message="Your restaurant has another table with that number.",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_of_guests__gt", 0)),
                name="number_of_guests_must_be_greater_than_zero",
                violation_error_message="Number of guests must be greater than zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="start_date_must_be_earlier_than_end_date",
                violation_error_message="Start date must come before end date.",
            ),
        ),
    ]
