from django.urls import path

from dinedashapp.views import (
    ChangeEmailView,
    ChangePasswordView,
    CreateMenuItemView,
    CreateOrderItemView,
    CreateReservationView,
    CreateReviewView,
    CreateTableView,
    DeleteReviewView,
    DeleteTableView,
    DeliveryLogInView,
    DeliveryRegistrationView,
    EditDeliveryAccountDetailsView,
    EditMenuItemView,
    EditOrderItemView,
    EditRegularAccountDetailsView,
    EditRestaurantInfoView,
    EditReviewView,
    ListOfReviewsView,
    ListOfTablesView,
    ManageOrder,
    ModifyFavoriteStatus,
    ModifyTableView,
    PlaceOrderView,
    RegularAccountView,
    RegularLogInView,
    RegularRegistrationView,
    ReservationDetailsView,
    ReservationsOfRegUserListView,
    RestaurantInfoView,
    RestaurantLogInView,
    RestaurantRegistrationView,
    RestaurantSearchView,
    about_us,
    blog,
    contact_us,
    delivery_orders_list,
    index,
    log_in_question,
    log_out,
    modify_reservation,
    regular_customer_orders_list,
    reservations_list,
    restaurant_orders_list,
)

urlpatterns = [
    path("", index, name="index"),
    path("about_us", about_us, name="about_us"),
    path("contact_us", contact_us, name="contact_us"),
    path("blog", blog, name="blog"),
    path("log_in_question", log_in_question, name="log_in_question"),
    path("log_in_regular", RegularLogInView.as_view(), name="log_in_regular"),
    path("log_in_restaurant", RestaurantLogInView.as_view(), name="log_in_restaurant"),
    path("log_in_delivery", DeliveryLogInView.as_view(), name="log_in_delivery"),
    path(
        "register_regular", RegularRegistrationView.as_view(), name="register_regular"
    ),
    path(
        "register_restaurant",
        RestaurantRegistrationView.as_view(),
        name="register_restaurant",
    ),
    path(
        "register_delivery",
        DeliveryRegistrationView.as_view(),
        name="register_delivery",
    ),
    path("log_out", log_out, name="log_out"),
    path("search", RestaurantSearchView.as_view(), name="restaurant_search"),
    path("restaurant/<int:pk>", RestaurantInfoView.as_view(), name="restaurant_info"),
    path(
        "restaurant/<int:pk>/favorite_status/<int:status>",
        ModifyFavoriteStatus.as_view(),
        name="modify_favorite_status",
    ),
    path(
        "restaurant/edit",
        EditRestaurantInfoView.as_view(),
        name="edit_restaurant_info",
    ),
    path(
        "restaurant/<int:restaurant_id>/reviews",
        ListOfReviewsView.as_view(),
        name="restaurant_reviews",
    ),
    path(
        "restaurant/<int:restaurant_id>/reviews/create",
        CreateReviewView.as_view(),
        name="create_restaurant_review",
    ),
    path(
        "restaurant/<int:restaurant_id>/reviews/edit",
        EditReviewView.as_view(),
        name="edit_restaurant_review",
    ),
    path(
        "restaurant/reviews/delete/<int:review_id>",
        DeleteReviewView.as_view(),
        name="delete_restaurant_review",
    ),
    path("menu/create", CreateMenuItemView.as_view(), name="create_menu_item"),
    path("menu/edit/<int:pk>", EditMenuItemView.as_view(), name="edit_menu_item"),
    path("account/change_email", ChangeEmailView.as_view(), name="change_email"),
    path(
        "account/change_password",
        ChangePasswordView.as_view(),
        name="change_password",
    ),
    path(
        "regular_account",
        RegularAccountView.as_view(),
        name="regular_account",
    ),
    path(
        "regular_account/edit",
        EditRegularAccountDetailsView.as_view(),
        name="edit_regular_account",
    ),
    path(
        "delivery_account/edit",
        EditDeliveryAccountDetailsView.as_view(),
        name="edit_delivery_account",
    ),
    path(
        "order/add/<int:menu_item_id>",
        CreateOrderItemView.as_view(),
        name="create_order_item",
    ),
    path("order/edit/<int:pk>", EditOrderItemView.as_view(), name="edit_order_item"),
    path("order/<int:pk>", ManageOrder.as_view(), name="manage_order"),
    path("order/<int:order_id>/place", PlaceOrderView.as_view(), name="place_order"),
    path("orders/restaurant", restaurant_orders_list, name="restaurant_orders"),
    path("orders/delivery", delivery_orders_list, name="delivery_orders"),
    path(
        "orders/regular", regular_customer_orders_list, name="regular_customers_orders"
    ),
    path("tables", ListOfTablesView.as_view(), name="restaurant_tables"),
    path("tables/create", CreateTableView.as_view(), name="create_restaurant_table"),
    path("tables/<int:pk>", ModifyTableView.as_view(), name="modify_restaurant_table"),
    path(
        "tables/<int:pk>/delete",
        DeleteTableView.as_view(),
        name="delete_restaurant_table",
    ),
    path(
        "restaurant/<int:restaurant_id>/reservation/create",
        CreateReservationView.as_view(),
        name="create_reservation",
    ),
    path(
        "reseveration/<int:pk>",
        ReservationDetailsView.as_view(),
        name="reservation_details",
    ),
    path(
        "reservations/regular",
        ReservationsOfRegUserListView.as_view(),
        name="regular_reservations",
    ),
    path("reservations", reservations_list, name="reservations"),
    path(
        "reseveration/<int:reservation_id>/edit",
        modify_reservation,
        name="modify_reservation",
    ),
]
